steps:

# TODO: separate build and deploy scripts
  - name: maven:3.8-openjdk-17
    entrypoint: mvn
    args: ["clean", "package", "-P", "prod", "spring-boot:repackage"]

  - name: 'gcr.io/cloud-builders/git'
    args: [ 'clone', 'https://github.com/informiz/iz-webapp.git' ]
  - name: 'gcr.io/cloud-builders/git'
    args: [ 'checkout', '${BRANCH_NAME}' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/iz-webapp/iz-webapp:$TAG_NAME', '.' ]

images:
- 'europe-docker.pkg.dev/$PROJECT_ID/iz-webapp/iz-webapp:$TAG_NAME'