apiVersion: apps/v1
kind: Deployment
metadata:
  name: iz-deployment
spec:
  selector:
    matchLabels:
      app: webapp
      channel: <CHANNEL_NAME>
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
        channel: <CHANNEL_NAME>
    spec:
      volumes:
      - name: service-account-creds-volume
        secret:
          secretName: <CHANNEL_NAME>-service-account-creds
      containers:
      - name: iz-webapp
        image: gcr.io/key-master-283113/iz-webapp:0.0.1-SNAPSHOT
        volumeMounts:
        - name: service-account-creds-volume
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: profile
          value: <PROFILE>
        - name: iz.webapp.key-id
          value: <CHANNEL_NAME>
        - name: iz.webapp.token.issuer
          value: <CHANNEL_NAME>
        - name: iz.webapp.token.audience
          value: <CHANNEL_NAME>
        - name: iz.webapp.token.secret
          valueFrom:
            secretKeyRef:
              name: <CHANNEL_NAME>-jwt-secret
              key: secret
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: <CHANNEL_NAME>-db-creds
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: <CHANNEL_NAME>-db-creds
              key: password
        - name: spring.security.oauth2.client.registration.google.client-id
          valueFrom:
            secretKeyRef:
              name: <CHANNEL_NAME>-oauth-creds
              key: client
        - name: spring.security.oauth2.client.registration.google.client-secret
          valueFrom:
            secretKeyRef:
              name: <CHANNEL_NAME>-oauth-creds
              key: secret
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
