apiVersion: v1
kind: Service
metadata:
  name: iz-webapp-service
  annotations:
      cloud.google.com/app-protocols: '{"iz-secure-port":"HTTPS"}'
spec:
  type: NodePort
  selector:
    app: webapp
    channel: <CHANNEL_NAME>
  ports:
  - name: iz-secure-port
    protocol: TCP
    port: 443
    targetPort: 8083